# Phone App Documentation

## 1. How to Setup
Once you are in the root folder of the project repo, type "npm start" on the command line. The expo browser tool will open in your browser. Then, you can choose to run the app on browser (as a website), Android device, or Apple device. For the spring 2021 semester final version, the code works best on an Android device (you can either use an emulator or a real device), and it works mostly on website. We haven't had a chance to test it on Apple device.

In order to configure the frontend to work with your firebase authentication,correct credentials need to be put into "config.js" file located in /src/FireBase. To work with your Amazon S3, change the corresponding data in the env.json file.

For the node.js backend, the root folder is at /backend/biometricBackend. Once you navigate there, you can type "node server.js" to start the server on port 3000.

In order to configure the backend to work with your MySQL database, correct credentials need to be put into "db.config.js" file located in /backend/biometricBackend/app/config.

## 2. Technologies Used
The phone app frontend is built with React Native and Expo. There are two backends. One is firebase, and the other is Nodejs. Firebase is used for login authentication. User's email and password are stored in firebase. Whenever the user wants to login, their provided credentials are checked against the values stored in the firebase.

The other backend is Nodejs. It is used to help the frontend communicate with the MySql database. It also helps the frontend store image to Amazon S3.

## 3. App Description
The app is divided into several different pages. Each page's description will be listed below:
### 3.1 Create Account Page
When user uploads an image, the image is stored to Amazon S3 through Nodejs. The frontend would receive part of the url (a number) that it can use to display the image. For now, the image url is not stored into the database yet, although it's stored in the frontend as a state variable. Once the user fills all the inputs and click the button, all the data, along with the image url, will be stored into the database (as a new row in the patient table). At the same time, an user is created at firebase, which is later used for authentication.

### 3.2 Login Page
When user fills in the info and click the login button, two things happen. First, the credentials are checked against the firebase auth. Then, the credentials are also used to retrieve the unique patient id from the SQL database, which will be used later as the patient's identifier to grab corresponding data from the SQL database.

### 3.3 Home Page
No communication with the backend happens on this page

### 3.4 Account Profile Page
Patient id is used to grab all the corresponding information from the SQL database and the info is displayed.

### 3.5 Edit Profile Page
Patient id is used to grab all the corresponding information from the SQL database and the info is displayed. The user can also modify the info and edit them in the SQL database. Once they edit it, the new info will be pulled again and displayed on the page.

### 3.6 Questionnaire Page
This page is used to create or edit a new row in the phone_app_data table. If you enter this page from the home page, you are going to execute a POST request, thus creating a new row. If you enter this page from Entries page, you are going to execute a PUT request, thus modifying an existing row. Once you click the create/modify button, you will automatically go back to the home page.

### 3.7 Entries Page
This page grabs all the rows with the current patient id in the phone_app_data table

## 4. API endpoints (how App frontend and Nodejs backend communicate)
| API url        | Task        |Frontend to Backend Data Format           | Backend to Frontend Data Format (return)          | Purpose  | Special Notes | Frontend Progress | Backend Progress |
| ------------- |-------------:| -------------:|:-------------:| -----:| -----: | -----: | -----: |
| /patient-questionnaire | POST | {patient_id: num, <br />happiness: num, <br /> sleep: num, <br /> hours_worked: num, <br /> unusual_symptoms: string, <br /> meals: num, <br /> medication_timing: num, <br />smoking_alcohol: boolean, <br /> other_medication: string, <br /> water_intake: num, <br /> diagnosis: string, <br /> image: string} | none | (used in Questions page) <br />when patient submits a questionnaire | backend creates "input_date" based on when it receives the API call and adds "input_date" column. This API fills everything in the phone_app_data table | Xin (complete) | Anav (complete) | 
| /image   | POST | ...   | ... | (used in any page that needs uploading image) <br /> This sends the image data to the server. The server sends back the key used to access the image on Amazon S3 |   | Xin (complete)  | Xin (complete) |
| /patient-account | POST | {first_name: string, <br /> last_name: string, <br /> username: string, <br /> email: string, <br /> gender: string, <br /> date_of_birth: string, <br /> height_cm: num, <br /> image: string} |  none | (used in Create Account page) <br />When user creates a new account |   | Xin (complete) | Xin (complete) |
| /patient-account/login | POST | {email: string} | {patientId: num} | (used in Login page) <br />When user logs in |   | Xin (complete) | Xin (complete) |
| /patient-account/{patientId} |  PUT | {first_name: string, <br /> last_name: string, <br /> username: string, <br /> email: string, <br /> gender: string, <br /> date_of_birth: string, <br /> height: num, <br /> image: string} | none | (used in Edit Profile page) <br />this modifies one row in the patient table |   | Xin (complet) | Xin (complete) |
| /patient-account/{patientId} |  GET | none | {patient_id: num, <br /> first_name: string, <br /> last_name: string, <br /> username: string, <br /> email: string, <br /> gender: string, <br /> date_of_birth: string, <br /> height: num, <br /> image: string} | (used in Profile page) <br />the server sends back one row of the patient table based on the given patient id | Used in Account Profile page | Xin (complet) | Xin (complete) |
| /patient-questionnaire |  GET | (as query) <br />?patientId | {input_date: string} | (used in View Entries page) <br />the server sends back all the entries belong to that patient | Used in Entries page | Xin (complete) | Anav (complete) |
| /patient-questionnaire | GET | (as query) <br />?patientId&dateTime |{patient_id: num, <br /> input_date: string, <br /> happiness: num, <br /> sleep: num, <br /> hours_worked: num, <br /> unusual_symptoms: string, <br /> meals: num, <br /> medication_timing: num, <br />smoking_alcohol: boolean, <br /> other_medication: string, <br /> water_intake: num, <br /> diagnosis: string, <br /> image: string} | (used in Entry Details page) <br /> the server sends back the specified entry | Used in Entry Details page | Xin (complete) | Anav (complete) |
| /patient-questionnaire | PUT | (as query) <br />?patientId&dateTime {patient_id: num, <br /> input_date: string, <br /> happiness: num, <br /> sleep: num, <br /> hours_worked: num, <br /> unusual_symptoms: string, <br /> meals: num, <br /> medication_timing: num, <br />smoking_alcohol: boolean, <br /> other_medication: string, <br /> water_intake: num, <br /> diagnosis: string, <br /> image: string}| none | (used in Entry Details page) <br /> the server sends back the specified entry | Used in Entry Details page | Xin (complete) | Anav (complete) |


## 5. Future Work
We are planning to experiment using Xcode to develop an Apple version of the app.