# Data Engineering Sprint #1

## Starting the Project and Introductions

Resuming the work done from the previous year’s data engineer team, each member briefly introduced themselves so that we would get to know each other better as we move forward with this project. During the first sprint, we mainly worked together as a team in order to review the current code and familiarize ourselves with it, as well as making sure all members understood the basics of python.

## Team Goals

The current code provides a great basis for innovation and streamlining the data collection process. Our current goals as a team are to extend the scope of the project to have compatibility with apple watches, ability to pull from multiple devices rather than a singular set device, and making the collection less intrusive.

## Looking Ahead: Accessing the Fitbit API Without Leaving Python

The current vision for this project is to create a bot that automatically runs the data collection code at specified intervals. However, leaving Python to open the browser authentication tab stalls the bot, and thus this step needs to be eliminated in the long run. 

One potential solution to this problem is with the Python library Selenium. Selenium allows for headless browser searching, meaning that a user can browse the web in Python without ever opening a search engine tab. The biggest foreseeable hurdle with implementing Selenium comes from needing to understand the inner workings of the Fitbit library source code. Simply substituting the Fitbit library’s web browser accessing function with Selenium’s browser opening function infinitely stalls the code. Research into implementing Selenium will continue to be done in future Sprint(s).

More information on Selenium can be found here: https://selenium-python.readthedocs.io. 

## Comparing health data available: Fitbit vs Apple 

Our team wanted to better understand what data was available from each company’s devices. As a note, we listed all the features that would be available from any device. We created the chart below to list the features available on each device. We found very similar data to be available on both devices. Further research in the next sprint will note what specific data is available on different generations/versions of each company’s Devices. 

                |                                       |Fitbit         |Apple Watch
 ---------------|---------------------------------------|---------------|---------------
 Activity       |Steps                                  |X              |X
                |Workouts                               |X              |X
                |Sit/Stand                              |X*             |NA
                |Flight Climbed                         |X              |X
                |Elevation                              |X              |X
                |Time spent in different activity levels|X              |X
                |Calories burned                        |X              |X
 Sleep          |Asleep vs Awake                        |X              |X
                |Stages                                 |X              |NA
 Heart Rate     |Time spent in different heart ranges   |X              |3rd party apps
                |Resting heart rate                     |X              |X
                |Walking Heartrate                      |NA             |X
                |Heart rate during activity             |X              |X
                |Intraday Tracking                      |5 sec          |10 min
 Nutrition      |Food log*                              |X              |X
                |Water log*                             |X              |X
 Body/Weight    |BMI*                                   |X              |X
                |Weight*                                |X              |X
 Additional     |ECG                                    |Coming soon    |X
                |Blood Oxygen                           |X              |X
                |Fall Detection                         |X              |X
                |Skin Thermometer                       |X              |NA
                |Ear Health                             |NA             |X
                |Stress Response                        |X              |NA
 ---------------------------------------------------------------------------------------
    *Entered manually
    NA = Not Available
 

With the Apple Watch, most data tracking is through the Health app and the files are exported as a .xml, which is difficult to read. However, you can also export your data through the Health app and have it opened in Numbers/Excel for easy viewing. For the FitBit, activity is recorded through the watch and outputs a .csv file when exporting, which is easy to read and open in applications like Excel and Numbers.

Additionally, it appears we are able to use Python in order to gather/sort data on both the Apple watch and Fitbit devices. Data is able to be read through pandas. Since Apple Watch returns a .xml file, we have to parse it first and use xmltodict module within Python before we can start applying functions to our data.

### Begin Investigation into the Apple SDK
Apple has created an entire software development kit meant to create applications for the Apple Watch. The main problem that our team faces is the need for a Mac OS to be able to create an app or use the SDK. There is a work around to this problem. Apple applications can be programmed using many third party softwares and even systems such as VirtualBox which allows a different OS to run on your computer. It is not confirmed yet whether using third party softwares, VirtualBox and etc. will allow the usage of Apple’s SDK. From further research, it appears that Apple has created a central repository for health and fitness data called the HealthKit. With HealthKit, the users can select what data they would like to share. The HealthKit has 5 main forms of data. Characteristic Data, things that do not typically change, Sample Data, most of the user’s health data, Workout Data, information about fitness and exercise activities, Source Data, each sample stores information about its source, and Deleted Objects.
# Getting Started     
To run BiometricFinal.py, it is recommended to download and install a true IDE (Integrated Development Environment) such as Visual Studio Code or PyCharm. It is possible to run the file through Anaconda and Spyder, but it is more complicated and may not work for any future modifications.

To run the code, first install Python (not through Anaconda) onto your machine. Next, open BiometricFinal.py in the IDE and open the Command Line associated with your IDE (Usually PowerShell for Windows and Terminal for Mac). In your Command Line, run the following commands: “pip install fitbit”, “pip install cherrypy”, and “pip install pandas” (note: pip is Python’s package manager which allows outside Python libraries to be installed). In addition, download gather_keys_oath2.py from https://github.com/orcasgit/python-fitbit and place the file in the same directory as BiometricFinal.py. If there are any errors about not having a certain dependency installed, you should be able to run BiometricFinal.py. This can be done by either running “python BiometricFinal.py” in your command line, or pressing the run button in your IDE. 

After running, a web page will be launched where you can log in with your FitBit credentials and the data will automatically be converted to a .csv file.
