--- 
title: "Wearables Book"
author: "Merck and Data Mine Corporate Partnership Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This a tutorial based book covering many foundational data science skills and using applying these skills to a complete, end-to-end project."
---

# Book Overview

A foundation of knowledge in the data sciences can prove advantageous for almost all scientists. Often, however, understanding the fundamentals of any new skill lacking proper instruction or recourses can be difficult. With ample guidance, all can develop a base knowledge of Data Science that can grow and provide new skills for improved research experiences. 

The sets of instruction, examples, and tutorials in this walk-through are specifically designed for Merck Technology and can be distributed to Merck Scientists. The walk-through will be tailored to the needs of the pharmaceutical industry and will relate to work being done at Merck.

In this walkthrough, a complete, end-to-end, project will be outlined with instructional and applicational opportunities throughout. 
