# Crontab via Python
The first thing we want to do is make sure we install the crontab module. Because the version of python differs,

the best way to install it is to use the pip command ie: (-pip install crontab) We also want to install datetime

and schedule so we can interpret integers as minutes/hours and and other time references. 

# Beginning Code

#
cron = crontab(user='root')
job = cron.new(command='scheduler.py')
#

This checks the user which is dependent on which user is running the code on their computers so it is subject to change. We also set job equal to the name of the python script.



# Cronjobs validity:
#
for jobs in cron:
    if (job.is_valid()):
        print (job)
job.is_valid()
job.enable(True)
#

This piece of code uses a for loop to iterate through the list of jobs we have stored in the list cron and checks if the job is valid.


# System restart:
#
job.every_reboot()
#

This code needs to be run everytime the system running the scheduler.py python script is shut down or restarted



